#! /bin/sh
### BEGIN INIT INFO
# Provides:          nfs-mount-exporter
# Required-Start:    $remote_fs avahi dbus nfs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NFS Mount Browser deamon
# Description:       This deamon publishes nfs shares over Avahi
### END INIT INFO

# Author: Mario Bielert <bugs@moonlake.de

test -x /usr/sbin/rpc.nfsd -a -f /etc/exports || exit 0

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="NFS Mount Exporter"

case "$1" in
  start)
	echo "Starting $DESC: nfs-mount-exporter."
 	nfs-mount-exporter.py & > /dev/null
	;;
  stop)
  	echo "Stopping $DESC: nfs-mount-exporter."
	kill $(pidof -x nfs-mount-exporter.py)
	;;
  restart|force-reload)
  	echo "Restarting $DESC: nfs-mount-exporter."
  	kill $(pidof -x nfs-mount-exporter.py)
  	nfs-mount-exporter.py & > /dev/null
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0