all:

clean:

install:
	cp nfs-mount-systray.py /usr/local/bin/nfs-mount-systray.py
	chmod +x /usr/local/bin/nfs-mount-systray.py
	cp Nfs\ Browser.desktop /etc/xdg/autostart/Nfs\ Browser.desktop

uninstall:
	rm /usr/local/bin/nfs-mount-systray.py
	rm /etc/xdg/autostart/Nfs\ Browser.desktop
