#       Copyright 2008 2009 2010 Mario Bielert <mario.bielert@googlemail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

all:

clean:

install:
	cp nfs-mount-systray.py /usr/local/bin/nfs-mount-systray.py
	chmod +x /usr/local/bin/nfs-mount-systray.py
	cp Nfs\ Browser.desktop /etc/xdg/autostart/Nfs\ Browser.desktop

uninstall:
	rm /usr/local/bin/nfs-mount-systray.py
	rm /etc/xdg/autostart/Nfs\ Browser.desktop
