#! /bin/sh
### BEGIN INIT INFO
# Provides:          nfs-mount-browser
# Required-Start:    $remote_fs avahi dbus
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NFS Mount Browser deamon
# Description:       This deamon browses for nfs shares over Avahi
### END INIT INFO

# Author: Mario Bielert <bugs@moonlake.de

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="NFS Mount Browser"

case "$1" in
  start)
	echo "Starting $DESC: nfs-mount-browser."
 	/usr/local/sbin/nfs-mount-browser.py & > /dev/null
	;;
  stop)
  	echo "Stopping $DESC: nfs-mount-browser."
  	if [ $(pidof -x nfs-mount-browser.py) > 0 ]; then
		kill $(pidof -x nfs-mount-browser.py)
	fi
	;;
  restart|force-reload)
  	echo "Restarting $DESC: nfs-mount-browser."
  	if [ $(pidof -x nfs-mount-browser.py) > 0 ]; then
		kill $(pidof -x nfs-mount-browser.py)
	fi
  	/usr/local/sbin/nfs-mount-browser.py & > /dev/null
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0